name: Update repo

on:
  workflow_dispatch:
  schedule:
    # Run at 00:00 (midnight) UTC on May 20th every year
    - cron: '0 0 20 5 *'
    # Run at 00:00 (midnight) UTC on June 1st every year
    - cron: '0 0 1 6 *'
    # Run at 00:00 (midnight) UTC on July 1st every year
    - cron: '0 0 1 7 *'
jobs:
  update_repo:
    runs-on: macos-13

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get files
        run: |
          curl -LO https://get.localhost.direct/localhost.direct.zip
          unzip -o -P localhost localhost.direct.zip
          openssl pkcs12 -export -out localhost.direct.pfx -inkey localhost.direct.key -in localhost.direct.crt -passout pass:
          rm localhost.direct.zip localhost.direct.crt localhost.direct.key

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: update certificate"
          add: localhost.direct.pfx